FROM python:3.10-slim

WORKDIR /app

RUN chmod -R 777 /app

COPY python/requirements.txt .

RUN pip install -r requirements.txt

ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} appuser \
    && useradd -u ${UID} -g ${GID} -m appuser

USER appuser

CMD ["python", "app.py"]