version: '3'

services:

  httpd:
    image: httpd:alpine
    container_name: httpd
    volumes:
      - ./website:/usr/local/apache2/htdocs
    ports:
      - "80:80"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  python:
    build:
      context: .
      dockerfile: dockerfile.python
    volumes:
      - ./python:/app
    working_dir: /app
    command: watchmedo auto-restart --debug-force-polling --directory=/app --pattern="*" --recursive -- python main.py
    ports:
      - "8000:8000"
      - "8765:8765"
    stdin_open: true
    tty: true
    depends_on:
      - redis
